### PR TITLE
Flink Source Connector for DynamoDB Streams

### PR DESCRIPTION
**Pull request by tinder-dthomson**
## What is the purpose of the change

*(For example: This pull request makes task deployment go through the blob server, rather than through RPC. That way we avoid re-transferring them on each deployment (during recovery).)*

## Brief change log

*(for example:)*
  - *The TaskInfo is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *TaskManagers retrieve the TaskInfo from the blob cache*

## Verifying this change

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (100MB)*
  - *Extended integration test for recovery after master (JobManager) failure*
  - *Added test that validates that TaskInfo is transferred only once across recoveries*
  - *Manually verified the change by running a 4 node cluser with 2 JobManagers and 4 TaskManagers, a stateful streaming program, and killing one JobManager and two TaskManagers during the execution, verifying that recovery happens correctly.*

## Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API, i.e., is any changed class annotated with `@Public(Evolving)`: (yes / no)
  - The serializers: (yes / no / don't know)
  - The runtime per-record code paths (performance sensitive): (yes / no / don't know)
  - Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Yarn/Mesos, ZooKeeper: (yes / no / don't know)
  - The S3 file system connector: (yes / no / don't know)

## Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by kali786516** [comment]
is this change merged into flink @tinder-dthomson ?

**Comment by tinder-dthomson** [comment]
@kali786516 yes, it is available in release 1.8.0!

**Comment by kali786516** [comment]
@tinder-dthomson  thanks for the reply, do you have a working example in public Github? it would help also maven dependency to import if required.

**Comment by tinder-dthomson** [comment]
@kali786516 I do not have an actual working public example (my code is not open sourced), but you can refer here for a simple usage: 

https://github.com/apache/flink/blob/master/flink-connectors/flink-connector-kinesis/src/test/java/org/apache/flink/streaming/connectors/kinesis/examples/ConsumeFromDynamoDBStreams.java

**Comment by kali786516** [comment]
@tinder-dthomson  saw that file looks like to get this import to work (
import org.apache.flink.streaming.connectors.kinesis.FlinkDynamoDBStreamsConsumer;
) I need to do below steps please confirm

Download :- 1.8 flink version https://github.com/apache/flink/archive/release-1.8.0.zip
mvn clean install -Pinclude-kinesis -DskipTests

**Comment by tinder-dthomson** [comment]
Instructions here: https://ci.apache.org/projects/flink/flink-docs-stable/dev/connectors/kinesis.html

The issue with the flink kinesis connector is that it's actually not available in maven. If you have a local maven repository you can reference it as you normally would, but you'll need to upload the jar yourself by building it and following the instructions above.

**Comment by kali786516** [comment]
@tinder-dthomson  thank you

**Pull request closed without merging**
